N2detailcollection:
    type: entity
    table: n2DetailCollection
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 50
            fixed: false
            nullable: false
    manyToOne:
        itemid:
            targetEntity: N2item
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                itemid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
